site_name: Qik
site_description: A cached command runner for Python monorepos.
docs_dir: docs

repo_name: Opus10/qik
repo_url: https://github.com/Opus10/qik

plugins:
  - search
  - blog
  - mkdocstrings:
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          - https://installer.readthedocs.io/en/stable/objects.inv
          - https://mkdocstrings.github.io/autorefs/objects.inv
          options:
            docstring_options:
              ignore_init_summary: true
            line_length: 80
            heading_level: 2
            merge_init_into_class: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: true
            show_root_members_full_path: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true

markdown_extensions:
  # For admonitions
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  custom_dir: docs/overrides
  name: material
  logo: static/logo.png
  favicon: static/logo.png
  features:
    - navigation.footer
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - css/mkdocstrings.css
  - css/mkdocs-material.css

nav:
  - Home: index.md
  - Guide:
    - Intro: guide.md
    - Commands: commands.md
    - Context: context.md
    - Caching: caching.md
    - CI/CD: ci.md
    - Troubleshooting: errors.md
  - Cookbook: cookbook.md
  - Blog: blog/index.md
  - Roadmap: roadmap.md
  - Release Notes: release_notes.md
  - Contributing: contributing.md
    
