modules = ["a", {name = "b_module", path = "b"}, "nest"]
plugins = [{name = "graph", path = "qik.graph"}]
deps = ["python_version"]

[caches.remote]
type = "s3"
bucket = "qik-cache-test"

[ctx.ci.qik]
workers = 1

[venvs.default]
lock-file = "requirements.txt"

[commands.fail]
exec = 'exit 1'

[commands.dep_fail]
exec = 'echo "hi"; exit 1'
deps = [{type = "command", name = "fail"}, {type = "const", val = "hi"}]

[commands.lock]
exec = "pip-compile > requirements.txt"
deps = ["requirements.in", {type = "dist", name = "pip-tools"}]
artifacts = ["requirements.txt"]
cache = "remote"
cache-when = "finished"

[commands.modular_lint]
exec = "ruff check {module.path}"
deps = [{type = "module", name = "{module.name}"}]
cache = "repo"

[commands.modular_format]
exec = "ruff format {module.path}"
deps = ["{module.path}/**.py", {type = "command", name = "modular_lint"}]
cache = "repo"

[commands.lint]
exec = "ruff check --fix && ruff format"
deps = ["**.py"]
cache = "remote"
